### PR TITLE
Update changelog for release

### PR DESCRIPTION
**Pull request by forrestfwilliams**

### CODE REVIEW

**Review by jtherrmann — CHANGES_REQUESTED** [review]
We've only released `0.1.0`: https://github.com/ASFHyP3/hyp3-isce2/releases
So we should collapse all of the subsequent Changelog entries into a single `0.2.0` release.
Let me know if I'm missing something obvious, happy to be corrected.

**Comment by forrestfwilliams** [comment]
Nope, you're right! I'm still learning how to write effective changelogs!

**Comment by forrestfwilliams** [comment]
@jtherrmann, ready for another look!

**Review by jtherrmann — APPROVED** [review]
LGTM!

**Pull request merged**
