### PR TITLE
Support HH processing

### LINKED ISSUE #168: S1 TopsApp processing (SLC or burst) cannot process SH (HH) scenes
**Jira:** https://asfdaac.atlassian.net/browse/TOOL-2451

*Note: The above link is accessible only to members of ASF.*

----------------------------------------------------------------------------------------------------

ISCE2 sets the default polarization to [`vv`](https://github.com/isce-framework/isce2/blob/main/components/isceobj/Sensor/Sentinel1.py#L95) so it will not be able to process `hh` scenes unless the `polarization` parameter is set for the `reference` and `secondary` scenes in the `topsApp.xml` (see [this discussion](https://github.com/isce-framework/isce2/discussions/495)), which we [do not do](https://github.com/ASFHyP3/hyp3-isce2/blob/develop/src/hyp3_isce2/templates/topsapp.xml).

Traceback:
```
2023-12-14 22:23:08,019 - hyp3_isce2.burst - INFO - SAFEs created!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/hyp3_isce2/__main__.py", line 51, in <module>
    main()
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/hyp3_isce2/__main__.py", line 47, in main
    sys.exit(process_entry_point.load()())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/hyp3_isce2/insar_tops_burst.py", line 477, in main
    isce_output_dir = insar_tops_burst(
                      ^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/hyp3_isce2/insar_tops_burst.py", line 93, in insar_tops_burst
    ref_footprint = get_isce2_burst_bbox(ref_params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/hyp3_isce2/burst.py", line 241, in get_isce2_burst_bbox
    s1_obj.parse()
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/isce/components/isceobj/Sensor/TOPS/Sentinel1.py", line 316, in parse
    self.validateUserInputs()
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/isce/components/isceobj/Sensor/TOPS/Sentinel1.py", line 238, in validateUserInputs
    raise Exception('No annotation xml file found in {0}'.format(dirname))
Exception: No annotation xml file found in /home/conda/S1A_IW_SLC__1SSH_20231103T035107_20231103T035135_051047_0627B4_9900.SAFE
```

### PR DESCRIPTION
**Pull request by jhkennedy**
Fixes #168

### CODE REVIEW

**Comment by jhkennedy** [comment]
Test pass, but processing this pair:
```
python -m hyp3_isce2 ++process insar_tops_burst \
     --looks 20x4 --apply-water-mask False \
    S1_238255_IW1_20230722T083342_HH_7C1C-BURST \
    S1_238255_IW1_20230815T083343_HH_642F-BURST
```
fails because the InSAR ROI (approximately the yellow box) appears to be outside of the granule footprint (red box) and no secondary directory gets created:
image

```
Traceback:
...
2023-12-14 17:40:37,984 - hyp3_isce2.insar_tops_burst - INFO - InSAR ROI: (149.7259071431545, -26.836642318851595, 149.7359071431545, -26.826642318851597)
2023-12-14 17:40:37,984 - hyp3_isce2.insar_tops_burst - INFO - DEM ROI: (149.7309071431545, -26.831642318851596, 150.77641044632287, -26.417374272428475)
...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/jhkennedy/Documents/Code/HyP3/hyp3-isce2/src/hyp3_isce2/__main__.py", line 51, in <module>
    main()
  File "/home/jhkennedy/Documents/Code/HyP3/hyp3-isce2/src/hyp3_isce2/__main__.py", line 47, in main
    sys.exit(process_entry_point.load()())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhkennedy/Documents/Code/HyP3/hyp3-isce2/src/hyp3_isce2/insar_tops_burst.py", line 478, in main
    isce_output_dir = insar_tops_burst(
                      ^^^^^^^^^^^^^^^^^
  File "/home/jhkennedy/Documents/Code/HyP3/hyp3-isce2/src/hyp3_isce2/insar_tops_burst.py", line 131, in insar_tops_burst
    topsapp.swap_burst_vrts()
  File "/home/jhkennedy/Documents/Code/HyP3/hyp3-isce2/src/hyp3_isce2/topsapp.py", line 124, in swap_burst_vrts
    raise ValueError(
ValueError: There should only be 2 VRT files in the reference and secondary directories, this indicates there is likely a bug in the region of interest generation.
```
VRTs:
``` python -m hyp3_isce2 ++process insar_tops_burst S1_238255_IW1_20230722T083342_HH_7C1C-BURST S1_238255_IW1_20230815T083343_HH_642F-BURST --looks 20x4 --apply-water-mask False
$ find . -iname '*.vrt'
./reference/IW1/burst_01.slc.vrt
./dem/full_res.dem.wgs84.vrt
```
structure on disk
```
$ tree -d
.
├── aux_cal
│   ├── S1A_AUX_CAL_V20190228T092500_G20210104T141310.SAFE
│   │   ├── data
│   │   └── support
│   └── S1B_AUX_CAL_V20190514T090000_G20210104T140612.SAFE
│       ├── data
│       └── support
├── dem
├── orbits
├── PICKLE
├── reference
│   └── IW1
├── S1A_IW_SLC__1SSH_20230722T083317_20230722T083345_049533_05F4C7_7C1C.SAFE
│   ├── annotation
│   │   └── calibration
│   └── measurement
└── S1A_IW_SLC__1SSH_20230815T083326_20230815T083354_049883_05FFFB_642F.SAFE
    ├── annotation
    │   └── calibration
    └── measurement
```

**Comment by forrestfwilliams** [comment]
The bug encountered here is the same as Issue #165. Essentially, the region we're using to enforce processing of exactly one burst is not being created correctly in some cases. In the original issue, the created region covers 2 bursts but in this case it is covering 0 bursts.

**Comment by AndrewPlayer3** [comment]
The problem was just a missing .tolower(). I tested the code locally and both HH and VV products are created successfully.

**Review by jtherrmann — APPROVED** [review]

**Comment by jhkennedy** [comment]
Oh  : facepalm:. Nice catch @AndrewPlayer3!

**Pull request merged**
